// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SortRollWebApp.Data;

#nullable disable

namespace SortRollWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250908100537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SortRollWebApp.Models.Entities.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.InitialParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSteelSection")
                        .HasColumnType("INTEGER");

                    b.Property<double>("L0")
                        .HasColumnType("REAL");

                    b.Property<double>("LR")
                        .HasColumnType("REAL");

                    b.Property<double>("P0")
                        .HasColumnType("REAL");

                    b.Property<double>("T0")
                        .HasColumnType("REAL");

                    b.Property<double>("T0max")
                        .HasColumnType("REAL");

                    b.Property<double>("T0min")
                        .HasColumnType("REAL");

                    b.Property<double>("TAU")
                        .HasColumnType("REAL");

                    b.Property<double>("TAU0")
                        .HasColumnType("REAL");

                    b.Property<double>("VK")
                        .HasColumnType("REAL");

                    b.Property<double>("W0")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdSteelSection");

                    b.ToTable("InitialParameters");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.Pass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("B0")
                        .HasColumnType("REAL");

                    b.Property<double>("B1")
                        .HasColumnType("REAL");

                    b.Property<double>("BD")
                        .HasColumnType("REAL");

                    b.Property<double>("BVR")
                        .HasColumnType("REAL");

                    b.Property<double>("H0")
                        .HasColumnType("REAL");

                    b.Property<double>("H1")
                        .HasColumnType("REAL");

                    b.Property<int>("IdSteelSection")
                        .HasColumnType("INTEGER");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PSI")
                        .HasColumnType("REAL");

                    b.Property<double>("R")
                        .HasColumnType("REAL");

                    b.Property<double>("R8")
                        .HasColumnType("REAL");

                    b.Property<double>("ROV")
                        .HasColumnType("REAL");

                    b.Property<double>("S")
                        .HasColumnType("REAL");

                    b.Property<double>("SP")
                        .HasColumnType("REAL");

                    b.Property<double>("SUMX")
                        .HasColumnType("REAL");

                    b.Property<int>("SchemaCaliber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaInput")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TOP")
                        .HasColumnType("REAL");

                    b.Property<double>("W")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdSteelSection");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.RollingMill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFactory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdFactory");

                    b.ToTable("RollingMills");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.RollingStand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AKL")
                        .HasColumnType("REAL");

                    b.Property<double>("C")
                        .HasColumnType("REAL");

                    b.Property<double>("DB")
                        .HasColumnType("REAL");

                    b.Property<double>("DSH")
                        .HasColumnType("REAL");

                    b.Property<double>("ETA")
                        .HasColumnType("REAL");

                    b.Property<double>("FPOD")
                        .HasColumnType("REAL");

                    b.Property<double>("IR")
                        .HasColumnType("REAL");

                    b.Property<int>("IdRollingMill")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LKL")
                        .HasColumnType("REAL");

                    b.Property<double>("MDOP")
                        .HasColumnType("REAL");

                    b.Property<double>("MU")
                        .HasColumnType("REAL");

                    b.Property<double>("NDVMAX")
                        .HasColumnType("REAL");

                    b.Property<double>("NDVMIN")
                        .HasColumnType("REAL");

                    b.Property<double>("NDVN")
                        .HasColumnType("REAL");

                    b.Property<double>("NNOM")
                        .HasColumnType("REAL");

                    b.Property<double>("NZ")
                        .HasColumnType("REAL");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PDOP")
                        .HasColumnType("REAL");

                    b.Property<double>("PP")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdRollingMill");

                    b.ToTable("RollingStands");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.Steel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("K1")
                        .HasColumnType("REAL");

                    b.Property<double>("K2")
                        .HasColumnType("REAL");

                    b.Property<double>("K3")
                        .HasColumnType("REAL");

                    b.Property<double>("K4")
                        .HasColumnType("REAL");

                    b.Property<double>("K5")
                        .HasColumnType("REAL");

                    b.Property<double>("K6")
                        .HasColumnType("REAL");

                    b.Property<double>("K7")
                        .HasColumnType("REAL");

                    b.Property<double>("K8")
                        .HasColumnType("REAL");

                    b.Property<double>("K9")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SteelCode")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Steels");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.SteelSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRollingMill")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdRollingMill");

                    b.ToTable("SteelSections");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.InitialParameters", b =>
                {
                    b.HasOne("SortRollWebApp.Models.Entities.SteelSection", "SteelSection")
                        .WithMany("InitialParameters")
                        .HasForeignKey("IdSteelSection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SteelSection");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.Pass", b =>
                {
                    b.HasOne("SortRollWebApp.Models.Entities.SteelSection", "SteelSection")
                        .WithMany("Passes")
                        .HasForeignKey("IdSteelSection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SteelSection");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.RollingMill", b =>
                {
                    b.HasOne("SortRollWebApp.Models.Entities.Factory", "Factory")
                        .WithMany("RollingMills")
                        .HasForeignKey("IdFactory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.RollingStand", b =>
                {
                    b.HasOne("SortRollWebApp.Models.Entities.RollingMill", "RollingMill")
                        .WithMany("RollingStands")
                        .HasForeignKey("IdRollingMill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RollingMill");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.SteelSection", b =>
                {
                    b.HasOne("SortRollWebApp.Models.Entities.RollingMill", "RollingMill")
                        .WithMany("SteelSections")
                        .HasForeignKey("IdRollingMill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RollingMill");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.Factory", b =>
                {
                    b.Navigation("RollingMills");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.RollingMill", b =>
                {
                    b.Navigation("RollingStands");

                    b.Navigation("SteelSections");
                });

            modelBuilder.Entity("SortRollWebApp.Models.Entities.SteelSection", b =>
                {
                    b.Navigation("InitialParameters");

                    b.Navigation("Passes");
                });
#pragma warning restore 612, 618
        }
    }
}
