pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                echo 'Hello again, jenkins'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('App_home/SortRollWebApp') {
                    sh 'ls -l'
                    sh 'docker compose build'
                }
            }
        }
        stage('Start Docker Container') {
            steps {
                dir('App_home/SortRollWebApp') {
                    sh 'docker compose up -d'
                }
            }
        }
    }
}